# Generated by Django 4.1 on 2024-03-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="skills",
            field=models.CharField(
                choices=[
                    ("JS", "JavaScript"),
                    ("React", "React"),
                    ("API", "API"),
                    ("Backend", "Backend"),
                ],
                max_length=50,
            ),
        ),
    ]
